### ISSUE TITLE
Частично обновляется информация на странице

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#10]
Предусловие:
1. Открыть главную страницу на сайте Macroeconomic Statistics Berezini Partners
2. Выбирать функцию "Custom"
3. В поле ввода "Select Currencies" выбирать валюты GBP,IDR, HKD
4. В поле ввода "Volatillity" задать нужный нам параметр волатильности 
5. Нажать на кнопку "Update"

Фактический результат:
1.По нажатию кнопки  "Update" отображаются новостные события по выбранным валютам, но в правой части поля остаётся график валюты USD ISM Non-Manufacturing Employment (Sep). 
2. График предыдущей просмотренной валюты не убирается автоматически и обновляется после клика на выбранную валюту

![image](https://github.com/pauloberezini/macro-ui/assets/147265455/de17c27f-4528-45f9-b485-ef0da9f854d6)

Ожидаемый результат:
1. По нажатию кнопки "Update" после заданных параметров информация на странице обновляется, в правом поле не отображается график предыдущей просмотренной валюты
2.  По нажатию на новостное события заданной валюты в правом поле отображается верная информация

**Comment by pauloberezini** [comment]
resolved in new version
