### ISSUE TITLE
Не обновляется информация на странице после заданных параметров

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#11]
Предусловие:
1. Открыть главную страницу на сайте Macroeconomic Statistics Berezini Partners
2. Выбрать функцию "Custom"
3. В поле ввода "Select Currencies" выбирать валюту  CAD
4. В поле ввода "Volatillity" задать нужный нам параметр волатильности 
5. Нажать на кнопку "Update"
 
Фактический результат:
1. По нажатию кнопки "Update" новостные события по данной валюте не обновляются
2. Остаётся информация по предыдущим заданным параметрам.

![image](https://github.com/pauloberezini/macro-ui/assets/147265455/8a69846c-0004-43cb-ba91-d8c69c05b5c2)

Ожидаемый результат:
1. По нажатию кнопки "Update" после заданных параметров в поле ввода "Select Currencies" и "Volatillity" информация на странице обновляется
2. Если нет новостных событий при заданных параметрах, то поле, где должна отображаться информация, остаётся чистым

**Comment by pauloberezini** [comment]
resolved in new version
