### ISSUE TITLE
Должен ли отображаться период

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#14]
Предусловие:
1. Открыть главную страницу на сайте Macroeconomic Statistics Berezini Partners
2. В поле меню выбрать раздел "Historical Macro
3. После нажатия на выбранный раздел открывается страница данного раздела
4. Выбрать FX
5. Ввести поле  "Enter a stock symbol" символ (валютную пару)
6. Нажать на кнопку "Get Data"

Фактический результат:
1. Если в поле ввести символ валюты EURSEK и нажать"Get Data",  то над кнопкой "Get Data" отображается период

![image](https://github.com/pauloberezini/macro-ui/assets/147265455/8e1dc424-ad37-40fe-8870-6b92e58bfd67)

2. Если в поле ввести символ валюты EURSEK=X и нажать"Get Data",  то над кнопкой "Get Data"  период не отображается
![image](https://github.com/pauloberezini/macro-ui/assets/147265455/54550469-3020-4e73-abac-968020c350dc)

Ожидаемый результат:
1. Ввести в поле "Enter a stock symbol" верный символ валюты
2. После нажатия "Get Data" получить корректную информацию

**Comment by pauloberezini** [comment]
get data process must be changed to new one, so process must include

1. Warning,Error,Success messages from BE
2. icon of loading
3. must be decided place of period to other one

**Comment by pauloberezini** [comment]
removed component
