### ISSUE TITLE
Графики на примере акции MSFT, валютной пары  GBPUSD Daily-pro ("Historical Macro")

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#15]
![image](https://github.com/pauloberezini/macro-ui/assets/147265455/2f591981-7fec-443b-9a70-080484e8182e)
![image](https://github.com/pauloberezini/macro-ui/assets/147265455/73e354fa-9639-4cd3-acad-f9e7e33e7254)

**Comment by pauloberezini** [comment]
Warning panel works like expected, but left side of the graph must be changed

**Comment by pauloberezini** [comment]
resolved
