### ISSUE TITLE
Раздел в меню "News"

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#16]
При клике на новостное событие, страница открывается в новой вкладке и переходит на основной источник информации. ! Но есть заголовки новостей,при клике на который, страница не открывается.
Пример : 04-10-2023 Dow Jones Futures Fall As Treasury Yields Keep Surging Toward 5%; Speaker McCarthy Ousted (ошибка 404). При клике на заголовок и переходе на новостной сайт, страница не открывается, Error 1009.                                                           
Пример: 03-10-2023 Dow Jones Slammed More Than 500 Points As House Speaker McCarthy Loses Confidence Vote Procedure. При клике на заголовок и переходе на новостной сайт, страница не открывается, Error 1009. 
![image](https://github.com/pauloberezini/macro-ui/assets/147265455/f7cb3b75-c012-422b-b768-cec6f85c191e)

**Comment by pauloberezini** [comment]
need to change deploy process like for prod

**Comment by pauloberezini** [comment]
deploy process  was changed, also was added information msg for events without data
