### ISSUE TITLE
Обнаружен атрибут popover.

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#18]
При клике на картинку на странице для спонсоров

![image](https://github.com/pauloberezini/macro-ui/assets/147265455/e7a483a3-63ac-4a08-8d39-a6918913b555)

отражается ошибка

![image](https://github.com/pauloberezini/macro-ui/assets/147265455/27e7a8e6-61d0-4971-9726-f457f8cde971)

**Comment by pauloberezini** [comment]
Thanks, it's not relevant to current project, it's a GitHub.com issue. Btw I hope it's works as expected:)
