### ISSUE TITLE
Отображается пустой график валюты JPY BoJ Summary of Opinions 

### ISSUE THREAD

**Issue by OlgaPckv** [pauloberezini/macro-ui#7]
Предусловие:
1. Открыть главную страницу на сайте Macroeconomic Statistics Berezini Partners
2. Выбираем событие из колонки "Event Name" и кликаем на название события валюты JPY BoJ Summary of Opinions
3. В правом поле отображается график

Фактический результат:
1. При клике на новостное событие  по валюте JPY BoJ Summary of Opinions открывается пустой график.                        
 Что он должен показывать?
![image](https://github.com/pauloberezini/macro-ui/assets/147265455/60fbe786-1dbe-4df0-9033-fe2e88bb0271)

Ожидаемый результат:
1. Привести в читабельный вид график, добавить пояснения к графику.

**Comment by pauloberezini** [comment]
resolved by #16
